// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postId"`
	ParentID *string    `json:"parentId,omitempty"`
	Content  string     `json:"content"`
	Author   *User      `json:"author"`
	Children []*Comment `json:"children,omitempty"`
}

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	Author          *User  `json:"author"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
